### PR TITLE
MDB extenstions

### PR DESCRIPTION
**Pull request by gandhiinfinera**
Added MDB specific handling in MGMT Framework HLD and other documentations

### CODE REVIEW

**Comment by sonic-otn** [comment]
@jjin62 please review it

**Comment by jjin62** [comment]
Looks fine to merge. Can we add some example of getNamespace() implementation? Not sure if there is better way than parsing the key value in URL?

**Review by sonic-otn — APPROVED** [review]
It looks good to me

**Comment by gandhiinfinera** [comment]
> Looks fine to merge. Can we add some example of getNamespace() implementation? Not sure if there is better way than parsing the key value in URL?

Thanks Jimmy
Will add a sample implementation for getNamespace

**Comment by jjin62** [comment]
The example looks good.

**Review by jjin62 — APPROVED** [review]

**Review by jjin62 — APPROVED** [review]
Approved.

**Comment by jjin62** [comment]
merged

**Pull request closed without merging**
